name: CI Pipeline

# Disparado em qualquer push no repositório
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixar o código do repositório
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurar o Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # Mudar para o diretório do projeto onde está o pom.xml
      - name: Change directory to project folder
        run: cd ProjetoGitHubActions  # Mude para o diretório correto, se necessário

      # Compilar o projeto com Maven
      - name: Build with Maven
        working-directory: ProjetoGitHubActions
        run: mvn clean package

      # Executar testes
      - name: Run tests
        working-directory: ProjetoGitHubActions
        run: mvn test

      # Salvar os artefatos da build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: maven-build
          path: ProjetoGitHubActions/target/*.jar
